[package]
name = "x402-reqwest-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
x402-reqwest = { version = "0.1.2" }
x402-rs = { version = "0.6.3" }
alloy = { version = "1.0.12" }
reqwest = { version = "0.12.20" }
tokio = { version = "1.45.1" }
dotenvy = { version = "0.15.7" }
